# Generated by Django 4.1.5 on 2023-02-18 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpu', models.BooleanField(blank=True)),
                ('mem', models.BooleanField(blank=True)),
                ('fan', models.BooleanField(blank=True)),
                ('hdd', models.BooleanField(blank=True)),
                ('pcie', models.BooleanField(blank=True)),
                ('bios', models.BooleanField(blank=True)),
                ('disk', models.BooleanField(blank=True)),
                ('fru', models.BooleanField(blank=True)),
                ('sdd', models.BooleanField(blank=True)),
                ('usb', models.BooleanField(blank=True)),
                ('id_light', models.BooleanField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 14, 48, 22, 304750)),
        ),
    ]
