# Generated by Django 4.1.5 on 2023-02-21 06:46

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testerApp', '0002_testitems_alter_users_addtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNTestLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Area', models.CharField(max_length=10)),
                ('Tester', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('SN', models.CharField(max_length=80)),
                ('Datetime', models.TimeField(default=django.utils.timezone.now)),
                ('MAC', models.CharField(max_length=80)),
                ('SAS', models.CharField(max_length=80)),
                ('FileUrl', models.CharField(max_length=100)),
                ('Operation', models.CharField(max_length=50)),
                ('CPU', models.CharField(max_length=50)),
                ('MEM', models.CharField(max_length=50)),
                ('DISK', models.CharField(max_length=50)),
                ('TID', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 14, 46, 51, 40699)),
        ),
    ]
